name: CI

on:
  pull_request:
    branches: 
      - develop
      - release
      - feature/**

jobs:
  build_job:

    runs-on: ubuntu-18.04
    timeout-minutes: 15
    strategy:
      matrix:
        node_version: [10.x, 12.x]
    env:
      NODE_ENV: "develop"
      PORT: "8080"  

    steps:
    - uses: actions/checkout@v2
    - name: Using node verson ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with: 
        node_version: ${{ matrix.node_version }} 
    - name: Run a multi-line script
      run: |
         npm install
         npm run build
         npm run test
